### ISSUE TITLE
Update CircleCI config to use Context variables

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#786]
Rather than using individual environment variables per project in CircleCI we should use Context variables which can span across all projects. This means updating the config file to specify the Context file to be used, like so:
```
workflows:
  test-build-and-deploy:
    jobs:
      - setup:
          context: JAC Context
      - test:
          context: JAC Context
          requires:
            - setup
```
